
Parameters:
  NetworkStackName:
    Description: VPC Stack Name to import the network details.
    Type: String

Resources:
  WebAppInstance1:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - AssociatePublicIpAddress: "True"
          DeviceIndex : 0
          SubnetId:
            Fn::ImportValue:
              Fn::Sub: "${NetworkStackName}-LBSubnet1ID"
          GroupSet:
            - Fn::ImportValue:
                Fn::Sub: "${NetworkStackName}-LoadBalancerSG"
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      KeyName: kpmg_challenge
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          echo "Hello World from $(hostname -f)" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: InterviewChallenge
  WebAppInstance2:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackName}-LBSubnet2ID"
      ImageId: ami-0b0dcb5067f052a63 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      KeyName: kpmg_challenge
      SecurityGroupIds:
        - Fn::ImportValue:
            Fn::Sub: "${NetworkStackName}-LoadBalancerSG"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          echo "Hello World from $(hostname -f)" > /var/www/html/index.html
      Tags:
       - Key: Name
         Value: InterviewChallenge

Outputs:
  WebAppInstance1:
    Description: The Instance Id - 1
    Value:
      Ref: WebAppInstance1
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-WebServer1'
  WebAppInstance2:
    Description: The Instance Id - 2
    Value:
      Ref: WebAppInstance2
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-WebServer2'